logging:
  level: INFO
  loggers:
    holidays: DEBUG
# start the server & app by running: java -jar target/holiday-0.0.1-SNAPSHOT.jar server config.yml
# in C:\Users\Gregor\IdeaProjects\TimeTracker

# Database settings.
database:
    # the name of the JDBC driver, mysql in our case
    driverClass: com.mysql.jdbc.Driver
    # the username
    user: time_tracking_app
    # the password
    password: tta676
    # the JDBC URL; the database is called holidays
    url: jdbc:mysql://localhost:3306/Time_tracking